#define ZTRAIT_CENTCOM_MAP "CentCom Station"
#define ZTRAITS_CENTCOM_MAP ZTRAITS_CENTCOM + list(ZTRAIT_CENTCOM_MAP)
#define ZTRAIT_INTERLINK_MAP "Interlink"
#define ZTRAITS_INTERLINK_MAP ZTRAITS_CENTCOM + list(ZTRAIT_INTERLINK_MAP)
